### ISSUE TITLE
run.py missing

### ISSUE THREAD

**Issue by RoyalTS** [yangsiy/Plask#4]
There doesn't appear to be a run.py in the repository so I'm at a bit of a loss as to how to get this running.

**Comment by WindyDarian** [comment]
```
#!flask/bin/python

from app import app

server_port = 80
server_ip = '0.0.0.0'

app.run(host = server_ip, port = server_port, debug = True)
```

Here is the code of run.py, you can add one yourself. I am not currently on a PC at the moment.
We dropped this file during our developing for some reason. I think it should be brought back now. 
Thank you!

**Comment by RoyalTS** [comment]
That works. Cheers!

**Comment by yangsiy** [comment]
Now we have added the run.py to repo.
