### ISSUE TITLE
Questionnaires without questions can trigger a bug

### ISSUE THREAD

**Issue by alex1007** [yangsiy/Plask#7]
In the admin portal, the questionnaires with no questions can be seen. When you try to open http://127.0.0.1:5000/quest/questionnaire/xxx, a bug will occur, since q.schema is None.

**Comment by yangsiy** [comment]
I cannot recur the issue you specified. 
Maybe you should describe the bug in detail, so that I can fix it.

**Comment by alex1007** [comment]
Create a questionnaire, but dont add questions. You will see the questionnaire in administrator view. When you try to check the questionnaire, the bug will occur.

**Comment by yangsiy** [comment]
Still cannot recur the bug.
When checking the questionnaire with 0 questions in the admin view, the website works properly on my local machine.
Maybe you can check configs in your environment or rebuild the database to check if the problem will occur. Thank you!
